name: "Windows CI Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        nginx:
          - 1.24.0
          - 1.23.2
          - 1.22.1
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: false
    - name: Windows build
      run: .scripts\ci-windows-build.bat ${{ matrix.nginx }}
    - name: Unit Tests
      run: .scripts\ci-windows-test.bat